disabled_rules:
  - nesting
  - trailing_newline
  - trailing_whitespace
  - todo
  - closure_parameter_position
  - unused_closure_parameter
  - mark
  - weak_delegate
  - empty_parameters

included:
  - Source

excluded:
  - Carthage
  - Pods
  - Configurations

line_length: 300
type_name:
  min_length: 
    warning: 3
    error: 2
  max_length:
    warning: 45
    error:  50

file_length:
  warning: 200
  error: 300
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 35
    error:  45
  excluded:
    - id
    - to
    - i
    - r
    - s
    - x
    - y

type_body_length:
  - 75 # warning
  - 150 # error

function_parameter_count:
  - 4 # warning
  - 5 # error

function_body_length:
  - 10 # warning
  - 20 # error
